#server.port = 8081
#spring.mvc.view.prefix = /WEB-INF/views/
#spring.mvc.view.suffix = .jsp

server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    backendA:
      baseConfig: default
      waitDurationInOpenState: 5000
    backendB:
      baseConfig: someShared